//! The parsed token generated by the lexer.

use std::fmt;

use text_size::TextRange;

/// Parsed token.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Token {
    /// The kind of the token.
    pub kind: TokenKind,
    /// The range in source text of the token.
    pub range: TextRange,
}

impl Token {
    pub fn new(kind: TokenKind, range: TextRange) -> Token {
        Token { kind, range }
    }
}

impl fmt::Display for Token {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}@{:?}", self.kind, self.range)
    }
}

/// Enum representing common lexeme types.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TokenKind {
    // Multi-char tokens:
    /// "// comment"
    LineComment,
    /// `/* block comment */`
    ///
    /// Block comments can be recursive, so a sequence like `/* /* */`
    BlockComment,
    /// Any whitespace character sequence.
    Whitespace,
    /// "ident"
    Ident,

    // Literals:
    /// "12_u8", "0o100", "0b120", "1".
    Int,
    /// "12.34", "1e3".
    Float,
    /// ""abc""
    Str,
    /// "r"abc""
    RawStr,

    // Keywords:
    /// "if"
    If,
    /// "else"
    Else,
    /// "loop"
    Loop,
    /// "while"
    While,
    /// "for"
    For,
    /// "in"
    In,
    /// "break"
    Break,
    /// "continue"
    Continue,
    /// "return"
    Return,
    /// "throw"
    Throw,
    /// "glo"
    Glo,
    /// "import"
    Import,
    /// "as"
    As,
    /// "is"
    Is,
    /// "not"
    Not,
    /// "and"
    And,
    /// "or"
    Or,
    /// "try"
    Try,
    /// "fn"
    Fn,
    /// "do"
    Do,
    /// "null"
    Null,
    /// "true"
    True,
    /// "false"
    False,

    // Three-char tokens:
    /// "==="
    Identical,
    /// "!=="
    NotIdentical,

    // Two-char tokens:
    /// "::"
    DoubleColon,
    /// "->"
    Arrow,
    /// "=="
    Eq,
    /// "!="
    NotEq,
    /// "<="
    LtEq,
    /// ">="
    GtEq,
    /// "+="
    AddAssign,
    /// "-="
    SubAssign,
    /// "*="
    MulAssign,
    /// "/="
    DivAssign,
    /// "%="
    RemAssign,

    // One-char tokens:
    /// ","
    Comma,
    /// "."
    Dot,
    /// "("
    OpenParen,
    /// ")"
    CloseParen,
    /// "{"
    OpenBrace,
    /// "}"
    CloseBrace,
    /// "["
    OpenBracket,
    /// "]"
    CloseBracket,
    /// "#"
    Pound,
    /// "?"
    Question,
    /// "!"
    Exclamation,
    /// ":"
    Colon,
    /// "="
    Assign,
    /// "<"
    Lt,
    /// ">"
    Gt,
    /// "|"
    VBar,
    /// "+"
    Add,
    /// "-"
    Sub,
    /// "*"
    Mul,
    /// "/"
    Div,
    /// "%"
    Rem,

    // Others:
    /// End of line (`\n`)
    Eol,
    /// End of input.
    Eof,

    // Errors:
    /// Unknown token, not expected by the lexer, e.g. "№"
    Unknown,
    /// Unterminated block comment, e.g. `/*`.
    UnterminatedBlockComment,
    /// An integer literal with only base prefix, e.g. `0x`.
    EmptyInt,
    /// An empty exponent in a float literal, e.g. `1.0e`.
    EmptyExponentFloat,
    /// A float literal with base prefix, eg. `0x1.0`.
    NonDecimalFloat,
    /// Unterminated string literal, e.g. `"abc`.
    UnterminatedStr,
}

impl TokenKind {
    pub fn is_trivia(self) -> bool {
        matches!(
            self,
            Self::LineComment | Self::BlockComment | Self::Whitespace
        )
    }

    pub fn is_error(self) -> bool {
        matches!(
            self,
            Self::Unknown
                | Self::UnterminatedBlockComment
                | Self::EmptyInt
                | Self::EmptyExponentFloat
                | Self::NonDecimalFloat
                | Self::UnterminatedStr
        )
    }
}

impl fmt::Display for TokenKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt::Debug::fmt(&self, f)
    }
}
